apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # <--- 明确打上 manual 的标签
  hostPath:
    path: /data/jenkins-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual  # <--- PVC 也拿着 manual 的标签去匹配
  resources:
    requests:
      storage: 10Gi
  volumeName: jenkins-pv
